server:
  port: 3344
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sujinfengee/springcloud-config # github上面仓库名称
          search-paths:
            - springcloud-config # git 上文件路径
          default-label: main # 默认分支
  rabbitmq: # 使用消息总线进行定点同步、广播同步配置需要 rabbitmq
    host: localhost
    port: 5672
    username: user
    password: password

# eureka
eureka:
  instance:
    prefer-ip-address: true # 使用IP注册服务
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 实例ID
  client:
    service-url: # 注册中心地址
      defaultZone: http://localhost:7071/eureka/,http://localhost:7072/eureka/

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh' # 暴露bus 刷新配置端点
