server:
  port: 8884
spring:
  application:
    name: sentinel-ribbon-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置 sentinel dashboard 地址
        dashboard: localhost:8858
        # 默认 8719，如果被占用则自动++
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'
