server:
  port: 8002

spring:
  application:
    name: cloud-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-alibaba-2022?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 123456

  zipkin: # 监控数据输出地址
    base-url: http://localhost:9411
    discovery-client-enabled: false # 关闭服务发现
    sender:
      type: web # 使用http传输数据
  sleuth:
    trace-id128: true
    sampler:
      probability: 1 # 采样频率（0~1）


eureka:
  instance:
    hostname: payment
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # eureka 向哭护短发送心跳的时间间隔，单位为秒（默认30s）
    lease-renewal-interval-in-seconds: 1
    # eureka 服务端在收到最后一次心跳后等待时间上限，单位为秒（默认90s），超时删除服务
    lease-expiration-duration-in-seconds: 2

  client:
    register-with-eureka: true # 不向服务中心注册自己
    fetch-registry: true # 不从服务端拉取服务
    service-url: # 注册地址
      defaultZone: http://localhost:7071/eureka,http://localhost:7072/eureka