server:
  port: 8006

spring:
  application:
    name: cloud-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-alibaba-2022?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 123456
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}